[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
memoise = "0.3.2"
num-complex = "0.4.0"
proconio = "0.4.3"
regex = "1.5.4"
z3 = "0.11.2"
